### ISSUE TITLE
is it possible to send 3 command on 2 device per 10ms

### ISSUE THREAD

**Issue by jasonbu** [Martinsbl/nrf5-mpu-examples#1]
in demo code ppi only used to send 1 command

**Comment by Martinsbl** [comment]
Unfortunately you can't change device address and pointers to the TX/RX buffers using PPI only. So writing and reading to two devices using just one TWI module or changing commands can only be done in software. I assume that you know that both nRF5 chips have two TWI modules which can work independently?

**Comment by jasonbu** [comment]
Unfortunately  two device with same pin, tks for reply, sloved with using interrupt
