### ISSUE TITLE
Missing include-files for nrf-ble-mpu-simple-example

### ISSUE THREAD

**Issue by RayBreslin** [Martinsbl/nrf5-mpu-examples#5]
Hello,

I was trying to set up the example "nrf-ble-mpu-simple" by including all relevant header- and source-files from the nordic-SDK (v12), but unfortunately I couldnt find any app_trace.h-/app_trace.c- and device_manager.h-/device_manager.c-files.

Were they only available in previous SDKs?

I would very much appreciate any help you can provide!

Regards Ray

**Comment by Martinsbl** [comment]
In SDK 12 the app_trace library was replaced with the Logger Module http://infocenter.nordicsemi.com/topic/com.nordic.infocenter.sdk5.v12.0.0/nrf_log.html?cp=4_0_0_3_15
It is quite advanced compared to app_trace so porting might take some time. Unfortunately I don't have the time to look into it in the foreseeable future.

**Comment by RayBreslin** [comment]
Thank you for that information - I kind of assumed that!

What about the device_manager-files? Have they been replaced too?

**Comment by Martinsbl** [comment]
Yes. The Peer Manager replaces the previous Device Manager. http://infocenter.nordicsemi.com/topic/com.nordic.infocenter.sdk5.v12.0.0/lib_peer_manager.html?cp=4_0_0_3_1_8

**Comment by RayBreslin** [comment]
Ah ok got it - example is running properly now with just minor modifications!

Thanks again! :)

**Comment by kbystedt** [comment]
Will you upload modifications?

**Comment by RayBreslin** [comment]
I could ofc, but I dont know if that actually helps, since its just an adaption for SDK v12.0+!

First I replaced the app_trace- and device_manager-functionality by the ones which Martin mentioned, but in my endversion I basically just removed all links and usages for either nrf_log and peer_manager since I had no use for them currently.
